### ISSUE TITLE
Crash when attacking certain mobs, enchants don't work, and pig doesn't drop sword on death.

### ISSUE THREAD

**Issue by blockerlocker** [DeflatedPickle/PigJousting#1]
Hi! This mod is hilarious and I figured I'd let you know about a few issues I experienced, as listed in the title:
- The game crashes when attempting to joust a cow, a cod, and a bat. I didn't test every mob, so there are probably more.
- Pig does not set mobs on fire when sword has Fire Aspect, and damage doesn't seem to be increased by Sharpness.
- Pig doesn't drop sword when killed.
- Cannot joust creepers.

Love this mod, super funny, thanks for making it!

**Comment by DeflatedPickle** [comment]
- [x] crashes - related to 2
- [x] not using enchantments - really dumb of me, used the wrong variable
- [x] item drops - i think i just forgot this
- [x] creeper participation - related to 2

thanks for letting me know!
